### ISSUE TITLE
EPIC: Documentation for docarray v2

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#1232]
# EPIC: DOcumentation 

what need to be done for docarray v2 release documentation wise : 

* add docstring testing : https://github.com/docarray/docarray/issues/1233
* add markdown testing via notebook run https://github.com/docarray/docarray/issues/1110
* Add a button to convert documentation to colab notebook for direct usage
* decide on a documentation tool : Mkdoc or readme
* Writre the rest of the documentation : tutorial, showcase, getting started ...

TODO :  
- [ ] fix inheritance : https://github.com/mkdocstrings/pytkdocs/issues/58#issuecomment-1475249881
- [ ] logo need to be change
- [ ] click text should go back to index page
- [ ] version tagging https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/ https://github.com/jimporter/mike
- [ ] add tabs where needed
- [ ] fix link 
- [ ] Add copyright and social like in v1 documentation
- [ ] edit on github button and view source
- [ ] repo  link on top right like in materials docs

**Comment by JoanFM** [comment]
Will close this and will create new tickets for Documentation
