### ISSUE TITLE
Evaluate DocArray 3d capability by creating a Dreamfusion Executor

### ISSUE THREAD

**Issue by samsja** [docarray/docarray#661]
# Context

DocArray support 3d data : https://docarray.jina.ai/datatypes/mesh/ But we rarely use it. We need to evaluate if it is still up to date to what people need.

A good way to evaluate is create an Executor for the popular text-to-3d generation model : [Dreamfusion](https://github.com/ashawkey/stable-dreamfusion).

At the end of this evaluation we should be able to say:

* Yes, DocArray 3d mesh support work fine with the current 3d application
or
* No, It does not play well and we need to change X points in the implementation to make it compatible
 

- [x] evaluate dreamfusion: https://github.com/jina-ai/docarray/issues/716
- [x] add vertices and faces representation: https://github.com/jina-ai/docarray/issues/708
- [x] add RGB-D image representation: https://github.com/docarray/docarray/issues/751 
- [ ] add texture information of mesh: https://github.com/jina-ai/docarray/issues/713
- [x] enable display() for 3d mesh data: https://github.com/jina-ai/docarray/issues/714
- [x] demo for new 3d data representation: https://github.com/jina-ai/docarray/issues/715

**Comment by numb3r3** [comment]
For the purpose of evaluation 3D data, I think we already had this use case https://github.com/jina-ai/executor-3d-encoder. But I agree that the generation model dreamfusion is a very interesting work we should follow.
